# Generated by Django 6.0.2 on 2026-03-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizez', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
