# Generated by Django 6.0.2 on 2026-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizez', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
