# Generated by Django 6.0.2 on 2026-03-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizez', '0003_quiz_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
