# Generated by Django 6.0.2 on 2026-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulus', '0002_post_email_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='addres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
