# Generated by Django 6.0.2 on 2026-03-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latihan', '0004_quiz'),
        ('questions', '0002_alter_answer_question_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latihan.quiz'),
        ),
    ]
