# Generated by Django 6.0.2 on 2026-03-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('body', models.TextField()),
                ('email', models.EmailField(default='nama@tanya.com', max_length=254)),
                ('addres', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
