# Generated by Django 6.0.2 on 2026-03-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField()),
            ],
        ),
    ]
