# Generated by Django 6.0.2 on 2026-03-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latihan', '0002_question_explanation_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Explanation',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
